"""ClickHouse DDL for the telemetry tables, generated from the feature contract.

``network_flows`` holds exactly what ``FlowFeatures.as_row()`` produces, and it is
generated here rather than maintained by hand for the same reason the Alembic migration
is: a column added to the contract and forgotten in the DDL means the sensor silently
drops a feature, and nothing would fail until a model was retrained on data that had a
hole in it.

Stdlib only, so ``core`` keeps its single dependency.
"""

from __future__ import annotations

from netsentinel_core.features.contract import (
    SCALAR_FIELDS,
    SPLT_IAT_FIELDS,
    SPLT_LEN_FIELDS,
)

#: Retention for raw telemetry (M2 s3.3). Long enough to investigate an incident,
#: short enough that a 128 GB disk survives a fortnight of lab traffic.
FLOW_TTL_DAYS = 30

#: Every scalar is Float64, matching the contract's own type. Packing counts into
#: smaller integers would save space at the cost of a conversion on every write and a
#: class of silent truncation bugs; ClickHouse compresses repeated values well enough
#: that the trade is not worth making.
SCALAR_TYPE = "Float64"


def network_flows_ddl(database: str = "netsentinel") -> str:
    """CREATE TABLE for the scored-flow table."""
    columns: list[str] = [
        "ts DateTime64(3)",
        "flow_id String",
        "sensor LowCardinality(String)",
        "src_ip IPv4",
        "dst_ip IPv4",
        "src_port UInt16",
        "dst_port UInt16",
    ]
    columns += [f"{name} {SCALAR_TYPE}" for name in SCALAR_FIELDS]
    # Signed lengths: negative means server to client, so Int16 is required.
    columns += [f"{name} Int16" for name in SPLT_LEN_FIELDS]
    columns += [f"{name} Float32" for name in SPLT_IAT_FIELDS]
    columns += [
        # Ground truth, only ever set for replayed or labelled captures.
        "label LowCardinality(Nullable(String))",
        # Null until the scorer has decided. Nullable on purpose: an undecided flow
        # must not be storable as 0, which would read as "confidently benign".
        "risk_score Nullable(Float64)",
        "shadow UInt8 DEFAULT 1",
    ]

    body = ",\n    ".join(columns)
    return (
        f"CREATE TABLE IF NOT EXISTS {database}.network_flows\n"
        f"(\n    {body}\n)\n"
        "ENGINE = MergeTree\n"
        "PARTITION BY toYYYYMMDD(ts)\n"
        # Ordered for the two queries that actually run: a time window, and
        # everything involving one host.
        "ORDER BY (ts, src_ip)\n"
        f"TTL toDateTime(ts) + INTERVAL {FLOW_TTL_DAYS} DAY\n"
        "SETTINGS index_granularity = 8192;"
    )


def suricata_events_ddl(database: str = "netsentinel") -> str:
    return (
        f"CREATE TABLE IF NOT EXISTS {database}.suricata_events\n"
        "(\n"
        "    ts DateTime64(3),\n"
        "    event_type LowCardinality(String),\n"
        "    signature_id UInt32,\n"
        "    signature String,\n"
        "    severity UInt8,\n"
        "    src_ip IPv4,\n"
        "    dst_ip IPv4,\n"
        "    flow_id String,\n"
        "    raw String\n"
        ")\n"
        "ENGINE = MergeTree\n"
        "PARTITION BY toYYYYMMDD(ts)\n"
        "ORDER BY (ts, signature_id)\n"
        f"TTL toDateTime(ts) + INTERVAL {FLOW_TTL_DAYS} DAY;"
    )


def zeek_logs_ddl(database: str = "netsentinel") -> str:
    return (
        f"CREATE TABLE IF NOT EXISTS {database}.zeek_logs\n"
        "(\n"
        "    ts DateTime64(3),\n"
        "    log_type LowCardinality(String),\n"
        "    uid String,\n"
        "    id_orig_h IPv4,\n"
        "    id_resp_h IPv4,\n"
        "    fields Map(String, String)\n"
        ")\n"
        "ENGINE = MergeTree\n"
        "PARTITION BY toYYYYMMDD(ts)\n"
        "ORDER BY (log_type, ts)\n"
        f"TTL toDateTime(ts) + INTERVAL {FLOW_TTL_DAYS} DAY;"
    )


def full_schema(database: str = "netsentinel") -> str:
    """Everything, in the order ClickHouse must run it."""
    header = (
        "-- Generated by netsentinel_core.features.clickhouse.\n"
        "-- Do not edit by hand: core/tests/test_clickhouse_ddl.py fails if this file\n"
        "-- and the feature contract disagree. Regenerate with\n"
        "--   python -m netsentinel_core.features.clickhouse > "
        "infra/clickhouse/init/01_schema.sql\n"
    )
    return "\n".join(
        [
            header,
            f"CREATE DATABASE IF NOT EXISTS {database};",
            "",
            network_flows_ddl(database),
            "",
            suricata_events_ddl(database),
            "",
            zeek_logs_ddl(database),
            "",
        ]
    )


if __name__ == "__main__":
    print(full_schema())
