-- Generated by netsentinel_core.features.clickhouse.
-- Do not edit by hand: core/tests/test_clickhouse_ddl.py fails if this file
-- and the feature contract disagree. Regenerate with
--   python -m netsentinel_core.features.clickhouse > infra/clickhouse/init/01_schema.sql

CREATE DATABASE IF NOT EXISTS netsentinel;

CREATE TABLE IF NOT EXISTS netsentinel.network_flows
(
    ts DateTime64(3),
    flow_id String,
    sensor LowCardinality(String),
    src_ip IPv4,
    dst_ip IPv4,
    src_port UInt16,
    dst_port UInt16,
    proto Float64,
    l4_src_port Float64,
    l4_dst_port Float64,
    duration_ms Float64,
    in_pkts Float64,
    out_pkts Float64,
    in_bytes Float64,
    out_bytes Float64,
    pkt_rate Float64,
    byte_rate Float64,
    bytes_per_pkt_in Float64,
    bytes_per_pkt_out Float64,
    bytes_ratio_out_in Float64,
    len_min_in Float64,
    len_max_in Float64,
    len_mean_in Float64,
    len_std_in Float64,
    len_min_out Float64,
    len_max_out Float64,
    len_mean_out Float64,
    len_std_out Float64,
    iat_min_ms Float64,
    iat_max_ms Float64,
    iat_mean_ms Float64,
    iat_std_ms Float64,
    tcp_syn_count Float64,
    tcp_ack_count Float64,
    tcp_fin_count Float64,
    tcp_rst_count Float64,
    tcp_psh_count Float64,
    tcp_urg_count Float64,
    min_ttl Float64,
    max_ttl Float64,
    splt_len_0 Int16,
    splt_len_1 Int16,
    splt_len_2 Int16,
    splt_len_3 Int16,
    splt_len_4 Int16,
    splt_len_5 Int16,
    splt_len_6 Int16,
    splt_len_7 Int16,
    splt_len_8 Int16,
    splt_len_9 Int16,
    splt_len_10 Int16,
    splt_len_11 Int16,
    splt_len_12 Int16,
    splt_len_13 Int16,
    splt_len_14 Int16,
    splt_len_15 Int16,
    splt_len_16 Int16,
    splt_len_17 Int16,
    splt_len_18 Int16,
    splt_len_19 Int16,
    splt_iat_0 Float32,
    splt_iat_1 Float32,
    splt_iat_2 Float32,
    splt_iat_3 Float32,
    splt_iat_4 Float32,
    splt_iat_5 Float32,
    splt_iat_6 Float32,
    splt_iat_7 Float32,
    splt_iat_8 Float32,
    splt_iat_9 Float32,
    splt_iat_10 Float32,
    splt_iat_11 Float32,
    splt_iat_12 Float32,
    splt_iat_13 Float32,
    splt_iat_14 Float32,
    splt_iat_15 Float32,
    splt_iat_16 Float32,
    splt_iat_17 Float32,
    splt_iat_18 Float32,
    splt_iat_19 Float32,
    label LowCardinality(Nullable(String)),
    risk_score Nullable(Float64),
    shadow UInt8 DEFAULT 1
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (ts, src_ip)
TTL toDateTime(ts) + INTERVAL 30 DAY
SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS netsentinel.suricata_events
(
    ts DateTime64(3),
    event_type LowCardinality(String),
    signature_id UInt32,
    signature String,
    severity UInt8,
    src_ip IPv4,
    dst_ip IPv4,
    flow_id String,
    raw String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (ts, signature_id)
TTL toDateTime(ts) + INTERVAL 30 DAY;

CREATE TABLE IF NOT EXISTS netsentinel.zeek_logs
(
    ts DateTime64(3),
    log_type LowCardinality(String),
    uid String,
    id_orig_h IPv4,
    id_resp_h IPv4,
    fields Map(String, String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY (log_type, ts)
TTL toDateTime(ts) + INTERVAL 30 DAY;

